name: Build and Check the unittests 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version

      - name: Install Salesforce CLI
        run: npm install -g salesforce-cli

      - name: Authenticate with Salesforce
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_YOM_BUILDER_URL }}  # Store your Salesforce Auth URL in GitHub Secrets
        run: sf auth:sfdxurl:store -f <(echo $SFDX_YOM_BUILDER_URL) -a YOMBuilder

      - name: Create scratch org
        run: sf org create scratch -f config/project-scratch-def.json -a YOMScratchorg -s -d 30

      - name: Push source to scratch org
        run: sf project deploy start -o YOMScratchorg

      - name: Run all unit tests
        run: sf apex run test --result-format human --wait 10 --code-coverage -o YOMScratchorg

      - name: Delete scratch org
        run: sf org delete scratch -o YOMScratchorg -p
